Feature branch
brytebee/NYT pull request #1
Opened 2021-01-13 16:26 UTC by brytebee

2021-01-13 18:08 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

- You've done some good progress so far.

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please remember to add a proper README file for this project.
- Please add a proper project description to this Pull Request!
- Please check the automatic linter tests that are failing in this Pull Request. There are a few, and you've done some good progress in this project, so I'll do a full code review instead of invalidating your project just yet. But please, remember to fix these linter errors!
- The New York Times logo at the top of the page should be an embedded image, not just text.
- The buttons at the right side of the top bar are too narrow on the sides. Please make them a bit wider to look more like the originals.
![image](https://user-images.githubusercontent.com/2739245/104491194-884b7000-5597-11eb-9ab2-3936260dd549.png)
- The images in your central section contain overflowing text. Please fix it:

![image](https://user-images.githubusercontent.com/2739245/104491490-eed08e00-5597-11eb-8f08-4c21db6975ed.png)

- Your top navbar should have a fixed position and stick to the top of the screen, like this (taken from the original page):
![image](https://user-images.githubusercontent.com/2739245/104491562-0ad42f80-5598-11eb-9b4b-d79ee56fd426.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-13 21:20 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @brytebee  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] In the navbar, you should have the NY Times image logo embedded in the centre (link to page) (screenshot from Pathwright)
* [ ] The NY Times logo in the navbar should be a link (link to page) (screenshot from Pathwright)
* [ ] Add some margin/padding to the `SUBSCRIBE NOW` and `LOGIN` buttons in the navbar.
* [ ] Your navbar should have a fixed position (it sticks to the top part of the screen) (link to page) (screenshot from Pathwright)
* [ ] You're expected to align elements with a combination of all three techniques (float, flex and grid). (Screenshot from Pathwright) and (Screenshot from Odin)

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-01-15 13:35 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Bright Atsighi** 
Good job with the improvements for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] The NY Times logo, in the navbar, should be a link.
- [ ] Your project should align elements with a combination of all three techniques (float, flex and grid).
- [ ] In your CSS file, group selectors with the same style definition.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-01-15 13:35 UTC, andresporras3423 commented on styles.css
> +}
Group this selector with the selector on line 242

2021-01-15 13:35 UTC, andresporras3423 commented on styles.css
> +}
Group this selector with the selector on line 253

2021-01-15 13:35 UTC, andresporras3423 commented on styles.css
> +}
Group this selector with the selectors on lines 331 and 116.

2021-01-15 15:02 UTC, Georjane requested changes
## Status: Changes Required 🔧
### Hi There ✋🏽
 Nice work so far team! However, you haven't made any of the changes required by the previous Code Reviewer. Please do and then submit for another code review.
Feel free to reach out to me on slack if you have any questions, Witah Georjane 🤝

Good luck on your project and Happy Coding 💻

2021-01-15 23:36 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2021-01-16 04:29 UTC, merged